### ISSUE TITLE
Custom element doesn't exist: ztm_stop_card.

### ISSUE THREAD

**Issue by jsiemek** [peetereczek/ztm-stop-card#2]
HA 0.106.5
arch | x86_64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.6
timezone | Europe/Warsaw
version | 0.106.5
virtualenv | false

browser log:
Uncaught (in promise) DOMException: Failed to execute 'whenDefined' on 'CustomElementRegistry': "ztm_stop_card" is not a valid custom element name
    at a (https://www.siemek.info:8123/frontend_latest/chunk.b5b99c32e8fe08e69155.js:2212:4034)
    at l (https://www.siemek.info:8123/frontend_latest/chunk.b5b99c32e8fe08e69155.js:2212:4369)
    at Hi (https://www.siemek.info:8123/frontend_latest/chunk.b5b99c32e8fe08e69155.js:4629:607)
    at HTMLElement.value (https://www.siemek.info:8123/frontend_latest/chunk.b5b99c32e8fe08e69155.js:5902:15172)
    at https://www.siemek.info:8123/frontend_latest/chunk.b5b99c32e8fe08e69155.js:5982:1566
    at Array.forEach (<anonymous>)
    at HTMLElement.value (https://www.siemek.info:8123/frontend_latest/chunk.b5b99c32e8fe08e69155.js:5982:1537)
    at HTMLElement.value (https://www.siemek.info:8123/frontend_latest/chunk.b5b99c32e8fe08e69155.js:5982:474)
    at HTMLElement.performUpdate (https://www.siemek.info:8123/frontend_latest/app.e0d83916.js:2:13852)
    at HTMLElement._enqueueUpdate (https://www.siemek.info:8123/frontend_latest/app.e0d83916.js:2:13331)

**Comment by jsiemek** [comment]
I solve it, easly:

in example it should be:

type: custom:ztm-stop-card

instead of:

type: custom:ztm_stop_card
